obj-$(subst m,y,$(CONFIG_ASUS_BATTERY_ME176C_CHARGER_BQ24192)) += platform_bq24192.o
obj-$(subst m,y,$(CONFIG_TOUCHSCREEN_GOODIX)) += platform_goodix.o
obj-$(subst m,y,$(CONFIG_USB_DWC3_PCI)) += platform_dwc3.o
obj-$(subst m,y,$(CONFIG_SND_SOC_INTEL_BYTCR_RT5640_MACH)) += platform_bytcr_rt5640.o
